In [1]:
import pandas as pd

In [2]:
from pathlib import Path
df = pd.read_csv(Path("data") / "spotify_data.csv")

In [3]:
df

,track_name,artists,track_genre,danceability,energy,valence,tempo,acousticness,liveness,instrumentalness,loudness,speechiness
0,Blinding Lights,The Weeknd,pop,0.514,0.730,0.334,171.005,0.00146,0.0897,0.000095,-5.934,0.0598
1,Save Your Tears,The Weeknd,pop,0.680,0.826,0.644,118.091,0.02120,0.5430,0.000011,-5.187,0.0300
2,Shape of You,Ed Sheeran,pop,0.825,0.652,0.931,95.977,0.58100,0.0931,0.000011,-3.183,0.0802
3,Perfect,Ed Sheeran,pop,0.599,0.448,0.168,95.050,0.16300,0.1060,0.000000,-6.312,0.0232
4,Someone You Loved,Lewis Capaldi,pop,0.501,0.405,0.446,109.891,0.75100,0.1050,0.000000,-5.679,0.0319
5,Stay,The Kid LAROI,pop,0.591,0.764,0.478,169.928,0.03830,0.1030,0.000000,-5.484,0.0485
6,Levitating,Dua Lipa,pop,0.702,0.825,0.915,103.012,0.05610,0.0674,0.000001,-3.787,0.0755
7,As It Was,Harry Styles,pop,0.520,0.731,0.662,173.930,0.34200,0.3110,0.001010,-5.338,0.0557
8,Bad Guy,Billie Eilish,pop,0.701,0.425,0.562,135.128,0.32800,0.1000,0.130000,-10.965,0.3750
9,Believer,Imagine Dragons,rock,0.776,0.780,0.666,124.949,0.06220,0.0810,0.000000,-4.374,0.1110
10,Take On Me,a-ha,rock,0.573,0.902,0.876,84.412,0.01800,0.0928,0.000001,-7.638,0.0543
11,Sweet Child O Mine,Guns N Roses,rock,0.451,0.943,0.629,125.618,0.08610,0.1160,0.000011,-5.321,0.0437

In [4]:
df_sample = df.sample(n=min(5000, len(df)), random_state=42)

In [5]:
feature_cols = ["danceability", "energy", "valence", "tempo", "acousticness", "liveness", "instrumentalness", "loudness", "speechiness"]
x = df_sample[feature_cols]
y= df_sample['track_genre']

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=42)

In [8]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 50,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [9]:
model.score(x_test, y_test)

0.6666666666666666

In [10]:
model.score(x_train, y_train)

1.0

In [11]:
from sklearn.dummy import DummyClassifier
baseline = DummyClassifier(strategy="most_frequent")
baseline.fit(x_train, y_train)

DummyClassifier(strategy='most_frequent')

In [12]:
baseline.score(x_test, y_test)

0.6666666666666666

In [13]:
baseline.score(x_train, y_train)

0.7777777777777778

In [14]:
pred= model.predict(x_test)

In [15]:
pred

array(['pop', 'pop', 'pop'], dtype=object)

In [16]:
pred= pd.DataFrame(pred)

In [17]:
pred

     0
0  pop
1  pop
2  pop

In [18]:
y_test

3      pop
7      pop
10    rock
Name: track_genre, dtype: object

In [19]:
pd.concat([pred, y_test], axis=1)

      0 track_genre
0   pop         NaN
1   pop         NaN
2   pop         NaN
3   NaN         pop
7   NaN         pop
10  NaN        rock

In [20]:
import joblib
joblib.dump(model, 'model.joblib')

['model.joblib']